### ISSUE TITLE
Exceptions are occasionally thrown on themes other than Kitten Rewards

### ISSUE THREAD

**Issue by ernieIzde8ski** [AnKing-VIP/anki-audiovisual-feedback#12]
Using the Flashcard or Silhouette themes causes Anki to throw an exception while clicking through cards. Anki continues to function, but an error notice is flashed on screen. I am getting about one error message every one to two cards.

```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.1.106_1-x86_64-with-glibc2.39

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.sound", line 298, in <lambda>
  File "aqt.sound", line 353, in _on_done
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "aqt.sound", line 297, in <lambda>
  File "aqt.sound", line 489, in _play
  File "aqt.sound", line 338, in _wait_for_termination
AttributeError: 'NoneType' object has no attribute 'returncode'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Audiovisual Feedback ['231569866', 2023-07-08T23:34, '0.8', mod]
Just Mono v2 ['91938993', 2024-01-06T05:31, 'None', '']
Progress bar - Visualize reviewed cards and remaining Fixed by Shige ['1708250053', 2024-08-14T13:28, 'None', mod]
ReColor ['688199788', 2024-03-02T20:45, '3.0', mod]
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1708250053 1771074083 231569866 688199788 91938993

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiDiscord - Discord integration for Anki ['1133851639', 2020-01-13T20:53, 'None', '']
```

**Comment by BlueGreenMagick** [comment]
Looks like Anki update changed the audio code. 

As a temporary workaround, you can turn off sounds in the config and the error shouldn't show up.

**Comment by BlueGreenMagick** [comment]
Sorry, I looked into it, and I couldn't reproduce the problem nor have any idea what could be causing this issue.

It's likely a race condition, but I can't figure out what it is racing against.

**Comment by BlueGreenMagick** [comment]
Looks identical to #6 actually. So it's not a recent thing.

**Comment by ernieIzde8ski** [comment]
Neat, guess this can be closed in favor of that issue
