### ISSUE TITLE
Error with rapid answers

### ISSUE THREAD

**Issue by DoctorToBeIn23** [AnKing-VIP/anki-audiovisual-feedback#6]
If you rapidly go through cards, then get the error. don't get the error when it's the only one on
but if I virtually turn on any other add on it bugs out again. Some times I need to rapidly go through
the cards and the click "D" to go to the decks home screen for the error to show up.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable
the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to
disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the
problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add
on author.
Debug info:
Anki 2.1.62 (bf05fae9) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.2.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-04-17 09:37:36
Caught exception:
Traceback (most recent call last):
File "aqt. taskman", line 122, in _on_closures_pending
File "aqt.taskman", line 71, in ‹lambda>
File "aqt.sound", line 297, in <lambda>
File "aqt.sound", line 351, in _on_done
File "concurrent.futures. _base", line 439, in result
File "concurrent.futures. base", line 391, in __get_result
File "concurrent.futures. thread", line 58, in run
File "aqt.sound", line 297, in ‹lambda>
File "aqt.tts", line 194, in _play
File "aqt.sound", line 336, in _wait_for_termination
AttributeError: 'NoneType' object has no attribute 'returncode'

**Comment by AnKingMed** [comment]
weird.. I'm ok sitting on this unless others have this issue
